version: '2'
# define all services
services:
  # our service is called atlas
  atlas:
    # Build directory.
    build:
      context: .
      # Dockerfile location
      dockerfile: ./docker/atlas/Dockerfile
    # apache is running on port 80 but we want to expose this to port 4000 on our local machine
    ports:
      - "4000:80"
    # we mount the working dir into the container, handy for development
    volumes:
      - .:/var/www/html/
  sass:
    build:
      context: .
      # Dockerfile location
      dockerfile: ./docker/sass/Dockerfile
    volumes:
      - ./webroot:/src
      - ./node_modules:/node_modules
